### ISSUE TITLE
attributes lost on name[@type='person']

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#1]
`name type="person"` has lost other attributes on conversion to `persName` - e.g. `@role, @ref, @key`. For examples see Bodl_0035, at` handNote`, or Buchanan_PJK_0036, at `decoNote`

**Comment by jamescummings** [comment]
Ooops that should only be happening when there is a single persName inside the name element.

@holfordm: Is it the case that these attributes are always on the surrounding name rather than the persName? Or is there a chance they might be on both? i.e. is it ok if I just get rid of any attributes that might be on the existing persName when I turn the name into a persName? Or do I need to figure out how to merge the two sets of attributes?

**Comment by jamescummings** [comment]
@holfordm It turns out there are only two originals where there is more than one element in a name with type='person'.  These are:
- Buchanan/Buchanan0002TEI_c1.xml
- Canon_Class_Lat/Canon_Class_Lat_0109.xml

And I find no attributes on persNames that are inside names.

Hence, I'm going to *not* change those two above to persName (leave them as name with type=person) and assume I can move any name attributes to persName. Changing in script.

**Comment by holfordm** [comment]
both cases are markup errors which I have now corrected, so it will be OK to convert these as well when I have committed and pushed.


________________________________

**Comment by jamescummings** [comment]
Just to note there is another side effect that will happen.  There are cases where there is text separate from the persName elements such as:

````
<name type="person">Queen <persName>Elizabeth II</persName></name>
````
Which I'm proposing just becomes:
````
<persName>Queen Elizabeth II</persName>
````

I could, of course, leave persName embedded inside persName if you thought that better.

**Comment by holfordm** [comment]
that should be OK


________________________________

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
