### ISSUE TITLE
convert2HTML: treatment of msItem\`@n`

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#106]
## Detailed Description
Currently if there is a '@n' on `<msItem>`, it only displays if there is also a `<locus>`. This creates problems when `<locus>` is not universally present as in the example below

## Link to Page
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_413

## Context
Looks amateurish

## Possible Implementation
if possible, display of `@n` should be in the template for `<msItem>` rather than `<locus>`. [alternatively n can be removed in these cases, but that would be less optimal]

**Comment by andrew-morrison** [comment]
So, the requirement is for all `msItem` elements that have been given an `@n` to be displayed with the contents of that, before the first child element, regardless of whether that individual one, or any of its sibling `msItem` elements, contains a `locus`? No `@n` means no numbering, whether deliberate or accidental.

If so, the problem is that the various elements that can be the first child of an `msItem` have previously been set up to be displayed with different HTML. Some output as a `div`, others `p`, some `span`. Changing that could have unindented consequences for their display elsewhere. But it means that simply moving the output of `@n` to the `msItem` template would, in some cases, make it appear on a line on its own, and in other cases display inline with the first item. For example...

```
1. Antoine de la Sale , Le petit Jehan de Saintré
Extract containing an account of the tournament b....

2.
(fols. 6v-7v)
Chronicle of France, 1403-1434
Rubric: Ci commence...
```
I could output the `@n` value in a `div`, so it's always on a line of its own, which may require a bit of CSS work if the line spacing or font sizes are inconsistent.

Ensuring the `@n` value is always inline is possible, just requires some complex XSLT. Not a huge amount of work, just worth asking what you want before proceeding.

**Comment by holfordm** [comment]
I think I need to see how the different possibilities look on screen (sorry...). Could we try: if the msItem first child is `<locus>`, then output the `@n' inline; otherwise, output it as a `<div>`?

**Comment by andrew-morrison** [comment]
I've implemented that, and updated the QA site.

As suspected, the CSS means the new numbering on non-locus items, in their own divs, are 16pt font size, while the numbering in line with the locus are 18pt. Not a big deal, and should be possible to fix.

One additional complication: I've set it up so there must be multiple sibling msItems with `@n` for it to display the numbering. Otherwise it adds "1. " to almost everything. This way, [only 2642 manuscripts](https://github.com/bodleian/medieval-mss/files/1547889/msitem_numbering_changed.txt) are affected by this change, instead of nearly all of them.

@holfordm: Let me know if this is OK, or you want to try something else.

**Comment by holfordm** [comment]
with CSS fix I think this will be OK, thanks. (Shall we leave the issue open as a reminder about the CSS or do you want to open a new issue for that?)

**Comment by holfordm** [comment]
Adding a reminder that this needs a CSS fix from @IgnatG

**Comment by IgnatG** [comment]
Oups - I'm on the case!

**Comment by IgnatG** [comment]
//fixed
