### ISSUE TITLE
history//region[@key] should index

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#107]
## Detailed Description
I noticed that places.xquery isn't indexing the `<region>` element which is used inside `<origPlace>`. Many of the regions don't currently have `@key` (partly because several are vague regions like 'North'), but several do (e.g. Normandy, Brittany), and I will add `@key` to those that need it but don't have it over the coming weeks.

**Comment by andrew-morrison** [comment]
This is a very simple change. I've tested it, and reindexed places on QA. It adds Burgundy, Brittany and Veneto. Anjou, Lombardy and Normandy were already being indexed, because there are manuscripts in which they are referenced as placeNames instead of regions, but their lists of links to manuscripts are increased.
