### ISSUE TITLE
Angle brackets being converted into HTML tags

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#111]
## Detailed Description
When angle brackets are used, presumably as part of some cataloguing notation, they are (correctly) escaped using the XML standard `&lt;` and `&gt;` entity references.

- These survive the transformation into HTML (the parser will have converted them to UTF-8 before the XSLT is applied, and converted them back on output) 
- When the XQuery pulls in the HTML and serializes it into the XML to send to Solr they become `&amp;lt;`  and `&amp;gt;`. That's necessary otherwise the Solr XML wouldn't be well-formed.
- They still appear that in that form when the record is viewed in the Solr management interface.
- But on the web site, they have been translated into UTF-8 characters for less-than and greater-than

That is OK (not valid HTML but web browsers can cope) if used on their own. But if what's been catalogued happens to also be a [HTML tag](https://www.w3schools.com/tags/tag_s.asp), it causes display issues.

## Link to Page
For example, everything after the word "Assignati" is displayed as struck-out on this page https://medieval.bodleian.ox.ac.uk/catalog/manuscript_3910 because that word is followed by `<s>` in the TEI file (meaning the s is optional?)

## Possible Implementation
Possibly this is an issue to be reported on the Blacklight GitHub page?

A workaround would be for people to use `&#10216;` and `&#10217;` when cataloguing, which are the numeric entity references for the UTF-8 characters described as "mathematical angle brackets". In most typefaces, those appear more more vertical. So you get `⟨s⟩` instead of `<s>`. But would that change the meaning of the notation, @holfordm?

**Comment by holfordm** [comment]
Thanks for flagging this. It relates to an older issue that we thought we had fixed https://github.com/bodleian/medieval-mss/issues/27 . This remaining problem relates to small number of MSS where angle brackets need to be replaced with `<supplied>`, which will then generate square brackets instead. 

However, it would be nice to have the ability to render `<supplied>` with angle brackets instead of square brackets, if desired (quite a lot of people indicate supplied text with angle brackets rather than square brackets) - so yes, it would be good to get this fixed in Blacklight if appropriate.

**Comment by ahankinson** [comment]
If it's just a rendering problem this could probably be handled with CSS for the 'supplied' tag.

**Comment by holfordm** [comment]
Note for @holfordm
Offending MSS:
Bywater 2
Christ Church 91, 92, 95, 103, 107, 110, 115, 121, 122, 342, 343, 378
Holkham Gr 2

**Comment by holfordm** [comment]
@IgnatG  Let me try and fix the data (I'll do it on Friday and it shouldn't take long) and I'll get back to you if there are any further problems.

**Comment by andrew-morrison** [comment]
There seem to be a few issues here:

- Data cleanup converting `&lt;s&gt;` into `<supplied>s</supplied>` to be done by @holfordm 
- The transformation of those into `[s]` isn't ideal. Can either be fixed by CSS to display as `<s>` or by XSL to display as `⟨s⟩`
- General problem (with Blacklight?) which could affect other contexts for using greater-than and less-than symbols.

**Comment by holfordm** [comment]
"The transformation of those into [s] isn't ideal. Can either be fixed by CSS to display as <s> or by XSL to display as ⟨s⟩" . I would prefer to do this in the XSL - I think it will be more reproducible for other projects. I am happy with mathematical angle brackets, but does @eifionjones have any thoughts from the Fihrist perspective?

**Comment by eifionjones** [comment]
Yep, mathematical angle brackets sound like a good solution to me

**Comment by andrew-morrison** [comment]
Done.

BTW, you might want to look at when `sic` and `choice` are used inside a `choice`. The XSL inserts square brackets for those, and also puts spaces in the wrong places (e.g. https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6230#MS_Holkham_misc_17-item8-item3)

**Comment by holfordm** [comment]
Data fixed via https://github.com/bodleian/medieval-mss/commit/726355df5187047a3128c5ed6e74bf3ae9032164
@andrew-morrison if you have a chance to reindex qa and prd in the next few days that would be much appreciated (I'm away from the office until next Monday)
I'll open a separate issue for sic and choice
