### ISSUE TITLE
full text search issue?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#122]
## Detailed Description
These may be isolated cases, but while checking data issues thrown up by the solr logs, I noticed that a keyword search for "Corbie" fails to return MS. Canon. Pat. Lat. 112 (http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_3682) where that place occurs. A search for "Chelles" does not return MSS. Douce 176 or Douce f. 1, in both of which the placename occurs. {Note that these two files have just been modified; the markup was previously `<settlement key="place_7008004">Chelles</settlement>, <orgName key="org_131247511">Benedictine nunnery</orgName>`)

Since these names will now be in the place name index, this may not be significant, I just thought it might be worth flagging in case it turned up any more fundamental issues with full text search.

**Comment by andrew-morrison** [comment]
I believe this has been fixed by some changes we recently made to the Solr configuration.

It became noticeable that the way it identified individual words while indexing was wrong while working on some of the smaller, much more sparsely-described catalogues. Those have fulltext indexes which barely makes it into the thousands of terms, so it is easier to spot problems. Medieval, in contrast, currently has 74,000 distinct terms in its fulltext index (after stemming, synonyms and stopwords have been applied.)

The examples given above have certainly been fixed. But if you find others, please re-open this issue.
