### ISSUE TITLE
Link Colours

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#128]
The colours for links to external services are the same as the surrounding text. This makes it difficult to know if you can click on something without first hovering over it.

## Link to Page

http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_6318

In this example, the links to Digital Bodleian and MLGB3 should be coloured the same blue as the other links. Currently it is black.

**Comment by IgnatG** [comment]
That's a formatting issue - the `a` tag contains a `span `in it with the text. There is no need for a span tag. 
I can colour it with blue as an anchor but ideal would be to take the span out

**Comment by ahankinson** [comment]
OK --- I will assign @andrew-morrison to handle this.

**Comment by andrew-morrison** [comment]
The HTML `span` is inside the `a` element because there is a TEI `title` element inside the `ref` element. The span has a class of "italic". In this case it is a bit redundant, but I could easily imagine another case where the link contains both a title and something else which shouldn't be displayed in italic, so in that case it would be useful. Writing XSL to cover all conceivable scenarios would be very complicated.

The problem seem to me to be that the CSS instruction to make text black (or a very dark shade of grey) is repeated many times, including for spans of class "italic". Surely just one `color` instruction should be defined for the body element (or possibly one of the `div` elements that contains all the contents) which would then cascade down to everything within?

**Comment by ahankinson** [comment]
Then this is a problem with the TEI?

**Comment by andrew-morrison** [comment]
No, the TEI is perfectly valid. 

I believe the quickest fix would be to remove `color: #0D0D0D;` from the `.italic` definition in app/assets/stylesheets/design/_individual_item.scss.

**Comment by holfordm** [comment]
Here is an example where only some content in the `bibl` element should be displayed in italic, as @andrew-morrison suggested
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_4518

**Comment by andrew-morrison** [comment]
Similarly complex bibliographic references - containing mixtures of titles, authors, dates, etc - can and do exist in other TEI catalogues too.

**Comment by IgnatG** [comment]
I can't remember why I had to add the `color: #0D0D0D;` part but it must have been a good reason. Anyway... I'll fix it. But before I do that, I'll need the HTML to be formatted appropriately. After that I'll Add default font sizes and colours to the whole page. 
See #129

**Comment by IgnatG** [comment]
this has been fixed now
