### ISSUE TITLE
What to do with new provenance information?

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#143]
Just opening an issue to discuss whether the new provenance information that the Mapping Manuscript Migrations project is going to add to the TEI files should be displayed or indexed differently. And if so, how? 

Regarding display, they will be displayed as extra paragraphs under a heading of "Provenance and Acquisition". Should those be split into two separate headings?

Regarding indexing, they will be indexed as free text, but should the date and/or the text be indexed in their own dedicated index fields, to boost their ranking, and maybe in the future be offered as a separate search field in an improved advanced search form?

**Comment by holfordm** [comment]
I am happy to leave the display as it is (i.e. with provenance and acquisition together).

Since the new information will include `@key` and `@role` for persons and organizations, the owners should appear in the person and place indexes and be filterable by role. I don't think we need to enhance the search in other ways. 

At a later stage, as you suggest, we might want to use the att.datable attributes on the `provenance` and `acquisition` elements in an improved advanced search form.

I'm going to open a separate issue about how the responsibility for the new information, which we will capture using `@resp`, might be displayed in the record
