### ISSUE TITLE
Display and indexing of msName elements

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/medieval-mss#144]
Currently, nothing is done with `msName` elements (alternative names for manuscripts as a whole.) Probably because they only appear in eight out of 9000+ Medieval TEI files.

An example is "The Bekynton anthology" in [MS. Add. A. 44](https://medieval.bodleian.ox.ac.uk/catalog/manuscript_66).

Because they are in the `msIdentifier`, they appear at the top of the page. But the XSL has no template to apply any specific style. They don't even get their own `p` tag.

They are indexed as free text only, so [searching for them](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=The+Bekynton+anthology) ranks other hits for the same keywords found in work titles much more highly. You have to [put them in quotes](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=%22The+Bekynton+anthology%22) to actually find them. Which seems odd given their prominence on the pages. I could add a new index field to boost their ranking, but their extreme rarity makes this a low priority. Or are these really famous appellations amongst researchers that really should be more easily findable?

They're even rarer in other catalogues, for example "The Book of Curiosities" in in [MS. Arab. c. 90 (Bodleian Library, Oxford University)](https://www.fihrist.org.uk/catalog/manuscript_783) is one of only four (two of which are in Oxford.)

**Comment by andrew-morrison** [comment]
FYI, here is a list of all the named manuscripts, at least according to the presence of an `msName` element:
```
Medieval    MS Add A 44             The Bekynton anthology
Medieval    MS Auct T inf 1 10      Codex
Medieval    MS Auct T inf 1 10      Ebnerianus
Medieval    MS Bodl 343             The Bodley Homilies
Medieval    MS Canon Bibl Lat 60    The Ranshofen Gospels
Medieval    MS Canon Class Lat 30   The Oxford Catullus
Medieval    MS Canon Class Lat 41   The Oxford Juvenal
Medieval    MS Junius 25            Murbach Hymnal
Medieval    MS Rawl C 813           The Welles Anthology
Islamic     MS Arab c 90            The Book of Curiosities
Islamic     MS Arab g 5 R           The Piggott Qurʼān
Hebrew      MS Kennicott 1          Kennicott Bible
Tibetan     MS Tibet a 9 R          Dakini Oral Lineage
Tibetan     MS Tibet b 1            Heruka Prayer
```

**Comment by holfordm** [comment]
Good questions. There are several other "names" that haven't been given `msName`, e.g the Ormesby Psalter, the Douce apocalypse, and so on. In some of these cases (e.g. Ormesby Psalter) it's been included in the work title, so it is easy to find; not so with the Douce apocalypse though - and that probably is a famous name that should be findable if you don't know the shelfmark. I don't know how many "names" there are for the whole collection, but maybe 50 or so?
I suggest:
- I will review the "named" manuscripts that should be findable by name (there is a book _Ocelli nominum_ that will help with this)
- for these manuscripts I will put the name both in the `msName` field and in the `head` field (so it will be displayed on the table of contents), and if appropriate in the work title
- the `msName` field should then be indexed so the results appear higher up, _but_ it won't be necessary to display the `msName` in the record, since it will already be there in the `head`.
How does that sound?

**Comment by andrew-morrison** [comment]
OK. Let me know when you've made the data changes and I'll changing the indexing.
