### ISSUE TITLE
index altIdentifiers (?)

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#155]
I'm not sure to what extent these are being indexed at the moment, but a search for Rawl D 783 doesn't return any  results - that ms. is part of https://medieval.bodleian.ox.ac.uk/catalog/manuscript_8391, and it would be good for this and similar mss. if a search for the shelfmark of a part returned the 'parent' item

**Comment by andrew-morrison** [comment]
`altIdentifier` elements are currently only being indexed if they have a type attribute of "internal". So, for manuscript_8391, it is indexing the summary catalogue numbers but not the shelfmarks for the parts, because those have no type attribute.

But I guess the only reason these are marked up using `altIdentifier` is because only one `idno` is allowed per `msIdentifier` by the TEI schema? If so, and these are proper shelfmarks, then I think the best fix would be to add them to the shelfmark index, rather than the one for alternative IDs like SCNs?

It makes little difference now, but might be better if a future advanced search form had a specific field for searching by shelfmark.
