### ISSUE TITLE
Ranking issue when search query includes a very common name

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#158]
A search for `john damascus` (no quotes) fails to return (at least on the first page of results) person_44435485, although that person's variants include 'St John, of Damascus' and 'John, of Damascus'

**Comment by andrew-morrison** [comment]
The record person_44435485 is ranked about 250th in a search for `john damascus` (no quotes), even restricted to just the people index, on the web site.

The same query run on the Solr backend returns it 9th in a search across everything.

person_2176 ("John of Damascus, pseudo") comes top in both.

The pp_variant_sm field isn't tokenized, but it is then copied to the fulltext field which is. person_44435485 has so many variant forms of his name it is unsurprising it is ranked lower than person_2176, because ranking is partly based on the number of hits divided by the total record size, but I cannot currently explain why person_44435485 is being ranked so poorly on the web site.

**Comment by andrew-morrison** [comment]
Searching for `Damascus` returns just the two person records above, so the issue is the very common name `John`

**Comment by andrew-morrison** [comment]
I've adjusted the configuration on the the QA server so _Johannes, Damascenus_ comes [second in a people-only search](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=person&q=john+damascus) and [eleventh in a search for anything](http://medieval-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=john+damascus).

Two things were required to achieve this:

- Removing `:sort => 'index'` from the `default_solr_params` in Blacklight's catalog_controller.rb file, which I think was interrupting [Solr/Lucene standard ranking algorithm](http://lucene.apache.org/core/3_5_0/api/core/org/apache/lucene/search/Similarity.html), specifically in this case Inverse Document Frequency, which favours documents that contain matches for the rarer term _damascus_ over the much more common term _john_. Reading the Blacklight documentation, I think that line should be used to reorder facets, not results
- Reducing the boosting for record titles (including person names) from a factor of 10 to a factor of 2

@holfordm: Please could you try some other queries on QA before I apply it to production.

**Comment by holfordm** [comment]
Seems to be fixed!
