### ISSUE TITLE
links to external sites

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#164]
## Detailed Description

1. Should links to external sites be distinguished visually from internal ones, e.g. with an external link icon? (I don't know what best practice is here, if there is a consensus).
2. Should links to external sites open in a new window/ tab? (see also #163)

**Comment by IgnatG** [comment]
1. It's the same for all links - no need for an external links icon. It's not necessarily a bad practice to add an icon next to it but it would overcomplicate things. 
2. Yes, external links should open in new tab. But if it's something from the data, then it's for @andrew-morrison

**Comment by andrew-morrison** [comment]
I've changed the XSL so that all external links in the manuscript description pages (not just ones to Digital Bodleian because of the back button issues noted #163) open in a new tab. This is on QA now but would be applied to production now if you did a re-index (it is not part of the improvements I've been working on in the processing-overhaul branch.)

However, because the mechanism is different, the external links in work/person/place pages (e.g. links to authorities like VIAF) added for #34 still open in the same tab. Consistency would be preferable but this requires some digging into the Blacklight code.

**Comment by andrew-morrison** [comment]
I've changed QA so that, for example here:

http://medieval-qa.bodleian.ox.ac.uk/catalog/person_89167647

...the external links open in new tabs.

Click on the manuscript and it doesn't open in a new tab. Scroll to the bottom and click on the JONAS link and it opens in a new tab.

Digital Bodleian links open in new tabs but summary catalogue images don't (because they're hosted on the catalogue web server.)

Zotero links open in a new tab, but I think they always have.

I think that leaves just the external links in the About page that all open in the same tab.

**Comment by IgnatG** [comment]
this should be done now. I've updated the About page as well
