### ISSUE TITLE
should `revisionDesc` display?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#165]
Adding information about significant changes to the record in `revisionDesc` seems a bit pointless if there is no way for users to see it. 
Not everyone will be interested in that information, of course, so it's display should probably be optional ('click here to see the revision history of this description').
@eifionjones raised the point that no-one will (probably) want to know about the changes made by James Cummings or other automated scripts. This could be dealt with by using a value of `@type` on `change` for records that should or shouldn't display.

**Comment by andrew-morrison** [comment]
It could be added, and a type attribute could determine whether to display of each change.

But if you want it to be revealed by clicking a button or link, that would require @IgnatG to develop some JavaScript/CSS, then tell me what HTML to enclose it in. For all the TEI catalogues.

I'm guessing this is fairly low priority, as all but a few `revisionDesc` contain only two things: a note of scripted batch conversion and "First online publication". Fihrist and the rest will be similar.

**Comment by ahankinson** [comment]
I'm not sure it's pointless to add the revision descriptions without displaying them. Once we get #22 in place, users will be able to see the data itself.

Also, all changes are already tracked by git, including when the change was made and who made it. Users can view the [change history](https://github.com/bodleian/medieval-mss/commits/master/collections/Christ_Church/Christ_Church_MS_90.xml) of every file to get the equivalent of a full revision description.

**Comment by holfordm** [comment]
It could still be useful to have someone like "date of first publication", "date of last substantive revision", so people can get a quick sense of whether / how a record has been edited recently. One possiblity would be to have something like a heading "Last substantive revision" followed by the most recent `<change>` from the revisionDesc.

**Comment by andrew-morrison** [comment]
I've updated QA to include the latest `change` element (i.e. most recent `@when` date - there are half a dozen where that isn't the same at the first listed). Take a look and let me know if you want this to go live in the next production re-index. I can tweak the formatting (e.g. italicize the dates?) but I cannot move them below the Zotero links.

6205 records have a latest change of "First online publication", "Record created", or similar. In 3306 it is the MMM addition of provenance information based on what is known about the collection the record is in. If you don't think the latter are substantive I could filter them out (presumably a lot of them would revert to "First online publication".)

I've set it up so they are not indexed, on the basis that users probably won't want to search for the contents of a change description. Also, if they were indexed, it would mean a lot of manuscripts would match for a search for _first folio_ (without quotes) for example, because of the _first_ in _First online publication_.

It is implemented as a Medieval-only customization, because in Fihrist the most recent template is quite often a left-over from the template used, and nothing to do with the actual record. And in other catalogues the only change is scripted changes by me or James Cummings.

**Comment by holfordm** [comment]
Thanks - I'll review shortly.

**Comment by holfordm** [comment]
@adunning any thoughts on this? changes visible at medieval-qa.bodleian.ox.ac.uk over VPN.

**Comment by adunning** [comment]
I think this is a great start. It would be nice to display the full list of changes – perhaps by not making them visible without an extra click, à la Wikipedia?

In an ideal world it would also be great to have a list of recent changes on the front page with an RSS feed.

**Comment by ahankinson** [comment]
The full list of changes can be seen in GitHub. If #22 is implemented, we could link to both the source and the changes. Something like “View TEI Source on GitHub (changes)” with the latter linked to the change list. 

If we were to expose that information it would be good to have a look at commit messages and come up with some expectations for what information goes in them. Currently they are quite broad, so they would not necessarily be informative to anyone looking at them.

Implementing a change publishing system could be done with GitHub Actions. I haven’t looked into them in too much detail, but it seems likely that they could be used to produce an RSS or Atom feed.

Can we go live with the current changes?

**Comment by holfordm** [comment]
Happy to go live.
