### ISSUE TITLE
treatment of `quote` element in html

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#169]
This description
http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_8834
= MS. Arch. Selden. A. 1
contains, in the provenance section, a `quote` element which is not being picked up correctly in the html conversion.
my intention was to render it as an indented paragraph, but perhaps this should be specified using a `@rend` attribute on the element? if so, what value?

**Comment by andrew-morrison** [comment]
There are quotes which should be displayed in line (in other TEI catalogues) but I think it would be best to determine which style to use based on context rather than have specific `@rend` values.

So I have changed the XSL (in the consolidated-tei-schema repository) to transform `quote` to `blockquote` in HTML if it is a sibling of a `p` or `note`. Previously, it only did so if it was a direct child of an `msItem`. So if you change MS_Arch_Selden_A_1.xml to this:
```
<provenance>
    <p>Dating to c. 1541 is based on ...</p> 
    <quote>it must have been about six years ago more or less...</quote>
    <p>Zavala (1938) and Gómez de Orozco (1941) believed ...</p>
</provenance>
```
Then it should display as an indented paragraph (with a grey bar down the left-hand side, which is extra style added by the CSS.)
