### ISSUE TITLE
HTML output contains spurious tags

### ISSUE THREAD

**Issue by ahankinson** [bodleian/medieval-mss#191]
View source on any manuscript record, and the HTML output will contain lots of `<?ni?>` tags. This is probably due to a problem with the TEI to HTML XSLT.

```
<div xmlns="http://www.w3.org/1999/xhtml" class="content tei-body" id="manuscript_182"> <div class="msDesc" id="MS_Add_E_3_R-msDesc1" lang="en"> <div class="msIdentifier"> <p>Summary Catalogue no.: <span class="idno">28527</span> </p> </div> <h3><?ni?>Contents<?ni?></h3> <div class="msContents"> <div class="msItem" id="MS_Add_E_3_R-item1"><span class="tei-title"><a href="/catalog/work_10057">Account of <span class="persName"><a href="/catalog/person_78992726">Sir John Williams</a></span>, treasurer of the jewels of <span class="persName"><a href="/catalog/person_172419710">Henry VIII</a></span> </a></span><div class="textLang"><span class="tei-label"><?ni?>Language(s):<?ni?> </span>English </div> </div> </div> <h3><?ni?>Physical Description<?ni?></h3> <div class="physDesc"> <div class="objectDesc"> <div class="form"><span class="tei-label"><?ni?>Form:<?ni?> </span>roll </div> <div class="support"><span class="tei-label"><?ni?>Support:<?ni?> </span>parchment </div> </div> </div> <h3 class="msDesc-heading3"><?ni?>History<?ni?></h3> <div class="history"> <div class="origin"><span class="tei-label"><?ni?>Origin:<?ni?> </span> <span class="origDate">1553</span> ; <span class="origPlace"> <span class="country"><a href="/catalog/place_7002445">English</a></span> </span> </div> </div> <div class="additional"> <div class="adminInfo"> <h3><?ni?>Record Sources<?ni?></h3> <div class="source">Summary description by Elizabeth Solopova and Matthew Holford, based on the Summary Catalogue and supplementary sources. <div class="listBibl"> <div class="bibl"><a href="/images/ms/aam/aam0505.gif">Summary Catalogue, Vol. 5, p. 470</a></div> </div> </div> </div> </div> </div> </div>
```

**Comment by andrew-morrison** [comment]
Those are processing instructions. The XSL adds them to instruct the XQuery not to index the certain parts of the manuscript pages, when it comes along afterwards and sucks all the text out of the HTML and into the fulltext index in Solr. Specifically, they're used to prevent standard headings and labels added by the XSL from being indexed.

For example, a [search for manuscripts containing _history_](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=manuscript&q=history) currently returns 142 hits. Without this is it would return about 9000 (almost all of the manuscripts because, except a few stub records Matthew has created for former shelfmarks, they all contain a section entitled "History" containing the date and place of origin.)

They exist outside the XML tree structure and should have no effect on anything else.
