### ISSUE TITLE
attribute values in `@role`

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#200]
practice in the medieval catalogue should be altered to conform with Fihrist, i..e. values of `@role` should be the three-letter LOC relator codes, not their expanded versions, e.g. 'fmo' not 'formerOwner'. 

this will enable us to simplify the guidelines and schema and allow for improved validation across the catalogues

this will require - (1) data fix for medieval TEI (2) some alterations to the indexing scripts. 

for (1), @andrew-morrison , is find-and-replace-in-files in Oxygen with the XPath filter set to `@role` the best way to do this?

**Comment by andrew-morrison** [comment]
Here are all the role values currently in the Medieval records:
```
   5903 formerOwner
    997 author
    490 scribe
    395 translator
    276 artist
    153 signer
    123 donor
    105 binder
     46 patron
     26 dedicatee
      4 commissioner
      3 uncertain
      2 stationer
      2 bookseller
      2 attributed
```
It includes a couple which don't appear on the web site ("uncertain" and "attributed") because they are roles on author elements, and aren't roles in the same sense.

Also I don't think the [MARC relators list](https://www.loc.gov/marc/relators/relaterm.html) has a code to distinguish commissioners from patrons. And there is no code for stationers (some combination or bookseller/printer/publisher?)

Oxygen's find and replace in files should work. There are no current values which are substrings of others, so it doesn't matter what order you do them in. Or you could let me know how to deal with the edge cases and I could write a script. It'd take about the same time.

I also need to edit the 3M mapping for the MMM project.

**Comment by holfordm** [comment]
TEI updated via 00cc0e9f89baeb2d2dd6e09d01da9c39c0bb71be

**Comment by andrew-morrison** [comment]
OK. If you re-index to QA it should work (because all the MARC relator codes are already in the script.) But if you want to keep the merging of, for example, three codes into a single "Owner, signer, or donor" option in the Roles facet on the web site, I need to modify the indexing script.

**Comment by holfordm** [comment]
I think it would be good to keep that merging.
