### ISSUE TITLE
surrogates that are not digital

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#209]
With restricted manuscripts in particular, it would be useful in the descriptions to mention non-digital surrogates (usually microfilm). What changes to the markup (if any) / XSLT would this involve?

**Comment by ahankinson** [comment]
I would imagine there would be a microfilm catalogue number associated with it? Would you be including that, or would you just want to say "Images of this MS are available on microfilm"?

Would you also want to include a link to somewhere that would identify the microfilm?

**Comment by holfordm** [comment]
Most of the microfilms are currently on open shelf at reference R. Films. 101, so the text would read something like "Microfilm: R. Films 101".
How about the following:
`
<surrogates>
<listBibl type="digital-facsimile">
<bibl type="digital-facsimile">  </bibl>
</listBibl>
<listBibl type="other">
<bibl type="microfilm">Positive microfilm (R. Films 101)</bibl>
</listBibl>
</surrogates>`

**Comment by andrew-morrison** [comment]
There are quite a lot of microfilm surrogates in Hebrew. For example, this:

https://hebrew.bodleian.ox.ac.uk/catalog/manuscript_316

Displays a subheading of "Microfilm" because it contains the following in `additional`:
```
<surrogates>
    <bibl>
       <idno n="MSS R.R. Film No." type="microfilm">F 19940</idno>
    </bibl>
</surrogates>
```
I think this is how they were originally catalogued. I didn't question the use of `@n` at the time.

I think the `@type` should go on the `bibl`. The XSL outputs headings of "Digital Images" and/or "Microfilm" but currently expects the `bibl` elements to be children of `surrogates`. So there's no need for `listBibl`, but it should be changed to work with that. In fact there's one example in Medieval, MS. Douce 231, which is not displaying its Digital Bodleian links because of that.

**Comment by andrew-morrison** [comment]
I've fixed the problem with `surrogates/listBibl/bibl`.

If you want to try adding microfilms, and see what it looks like on QA. The `@type` can be on `bibl` or `idno`.

**Comment by ahankinson** [comment]
Has this been fixed?
