### ISSUE TITLE
cit/quote elements inside incipit

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#231]
the cit and quote elements are used inside the incipit element to indicate the biblical quotes which are the 'lemmata' for sermons. Could the `quote` element inside `incipit` (either as a child or as a child of `cit` child of `incipit`) display in italic, which is the convention for these lemmata in a printed catalogue?

**Comment by andrew-morrison** [comment]
How about these:
```
<incipit type="lemma">ὡϲ κακοῦργοϲ ὁ δίκαιοϲ</incipit>
```
Should that whole incipit be italicized?

**Comment by holfordm** [comment]
yes please!

**Comment by andrew-morrison** [comment]
I have re-indexed Medieval QA with this change. Here are the affected records:

 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1050
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_985
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1745
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_1849
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10112
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10196
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10197
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10200

I'll re-index PRD at 5pm unless I hear otherwise.

I had to [fix a missing shelfmark](https://github.com/bodleian/medieval-mss/commit/26ad94889f954da99a8634a9230abb7965c4331e), as the indexing script wouldn't run without it, but otherwise there were no warnings.

**Comment by holfordm** [comment]
Could we please extend this to apply to the same elements in the `explicit` element?

**Comment by andrew-morrison** [comment]
I've made that change and re-indexed QA. Here are the affected records:

 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_7042
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_7106
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_7514
 * http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_10286
