### ISSUE TITLE
bibl type="SC", "QUARTO"

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#3]
in `<source>`, `bibl @type="SC"` or `@type="QUARTO"` have both changed to `bibl @type="related"`

**Comment by jamescummings** [comment]
Now that is weird.  Can you give me an example or two to check?

The XSLT at that point is

````
   <!-- bibl/@type -->
   <xsl:template match="bibl/@type">
     <xsl:variable name="type">
       <xsl:choose>
         <xsl:when test=".='commentedOn'">commentary</xsl:when>
         <xsl:when test=".='digitised-version' or .='related-items' or .='realted-volumes' or 'related-volumes' or .='referred'">related</xsl:when>
         <xsl:when test=".='extracts'">extract</xsl:when>
         <xsl:when test=".='ms'">MS</xsl:when>
         <xsl:when test=".='textual-relations'">text-relations</xsl:when>
         <xsl:when test=".='translated'">translation</xsl:when>
         <xsl:otherwise><xsl:value-of select="."/></xsl:otherwise>
       </xsl:choose>
     </xsl:variable>
<xsl:attribute name="type"><xsl:value-of select="$type"/></xsl:attribute>     
   </xsl:template>
````
Where I am indeed creating some as 'related' but only things that were similar to it (and often in such low numbers), or normalising extracts to extract or similar.  SC and QUARTO should all be hitting the `<xsl:otherwise>` which just puts out what it currently is.



Other normalisations:
- `decoNote/@type`: 
  - borderInitials or frieze to 'border';
  - decoration, paratext, printmark, secondary, unspecified or uwan to 'other' (though maybe I should let unwan through?)
  - diagrams to 'diagram'
  - ms to 'MS'
  - initial_border or initials to 'initial'
- `dimensions/@type`: 
  - 'number of folia' to 'folia'
  - ruledColumn or ruling to 'ruled
  - leaves to 'leaf'
  - ms to 'MS'
  - unknown to 'other' (though maybe I should keep unknown?)
- `name/@type`: 
  - artist to person (Though I should just convert artist to persName shouldn't I!)
  - church or corporate to 'org' (Though I should just convert church to orgName shouldn't I!)
  - ms to MS
- `title/@type`:
  - removed when empty
  - alternative or parallel to 'alt'
  - general or uniform to 'main'

Let me know if you object to any of those (they were what I put in my report I think). To see attribute usage and how many of what values have a look at http://research.it.ox.ac.uk/MSS/oxford.html

**Comment by jamescummings** [comment]
XSLT updated so that in next iteration `name/@type='church' and 'artist'` are converted to orgName and persName respectively.

**Comment by holfordm** [comment]
e.g Rawl_A_0005


By the way, please don't change "commentedOn" to "commentary".

bibl type="commentedOn" encloses a reference to a text commented on by the text in the manuscript

bibl type="commentary" means that there is a commentary in the manuscript that it was difficult to encode in msItem (e.g. "Psalms with commentary of Gilbert de la Porree).


I think the bug is in the second when of the XSLT where there is a .= missing, this seems to result in patterns not by other whens being matched to related for some reason. E.g. in Laud_misc0254 bibl type="commentedOn" has gone to "related" as well.


________________________________

**Comment by jamescummings** [comment]
Ah! Well-spotted! That may well be it.

I've commented out commentedOn. For reference numbers for type on bibl before conversion are:
type (18847) ="LYELL (496) | MS (213) | QUARTO (6388) | SC (8911) | abridgement (1) | bible (167) | commentedOn (640) | digitised-version (14) | edition (10) | extract (3) | extracts (3) | intervening (1) | ms (5) | realted-volumes (2) | referred (2) | related (28) | related-items (136) | related-volumes (46) | repertory (4) | text-relations (1747) | textual-relations (13) | translated (14) | translation (3) "

Do you have suggestions about normalising some more of these? abridgement? edition? intervening? repertory?

**Comment by holfordm** [comment]
I thought I had standardised more of these. Oh well.
abridgement, extract, extracts, intervening, translated, translation -> related

repertory, ms, we should keep as they are. 

I don't use related-items, related-volumes, text-relations, so don't want to comment on those... 

I will open a separate ticket about the other normalisations.

**Comment by jamescummings** [comment]
Do remember this is across all the catalogues, so you aren't to blame for some of them.  On new ticket I'll put the numbers for each type attribute value.

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
