### ISSUE TITLE
Indexing contributors

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#301]
It would encourage more people to contribute to the catalogue if they could have a link they could add to their CV etc. showing the entries they have provided.

In an ideal world, it would be brilliant if people could simlpy add their ORCID ID to the responsibility statement – e.g. `<persName ref="https://orcid.org/0000-0003-0464-5036">Andrew Dunning</persName>` – and have the system index these. The contributors' page could then display the manuscripts in which this person is involved, perhaps along with the contents of `<resp>`.

**Comment by andrew-morrison** [comment]
There's no harm in adding a `ref` attribute to your `persName`, and encouraging others to do so. If it catches on, we can index it, and start thinking about where on the web site to display them.

There is also this: https://github.com/bodleian/medieval-mss/graphs/contributors

**Comment by ahankinson** [comment]
The revision description, responsibility statement, and edition statement sections are probably sufficient for this purpose. I would not recommend indexing the git log since I'm not sure we want to make a contribution statement about fixing typos and formatting, and, as Andrew points out, GitHub already provides a mechanism for this.
