### ISSUE TITLE
Shorten URLs

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#302]
At the moment a manuscript URL appears in the format of `https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6923`: there has been some question as to why we are using American spelling in this. Could we shorten the URLs to remove this, perhaps into the form `https://medieval.bodleian.ox.ac.uk/manuscript/6923`?

**Comment by andrew-morrison** [comment]
The plan is to introduce [ARKs](https://en.wikipedia.org/wiki/Archival_Resource_Key), which would mean URLs something like `https://medieval.bodleian.ox.ac.uk/ark:/29072/srd3hk97rg8w` (although the length and level of obfuscation of the last part is up for discussion.) But obviously we'd need to keep the existing `https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6923` URLs working alongside for the foreseeable future, because they're already out there in citations and bookmarks. Adding a third set of URLs in the interim would probably not be a good idea.

**Comment by ahankinson** [comment]
We are using American spelling because this was imposed on us by Blacklight. Since we already publish (and [other projects](http://mappingmanuscriptmigrations.org) make use of our URI/URLs, we cannot change them until we have our ARK mechanism in place. (And even then, as @andrew-morrison points out, we will still need to keep the old URLs intact to ensure the stability of our references for readers who have already cited these pages).

**Comment by adunning** [comment]
I wasn't aware of the ARK scheme; that certainly makes more sense.
