### ISSUE TITLE
Contents of <head> not searched?

### ISSUE THREAD

**Issue by adunning** [bodleian/medieval-mss#347]
[MS. Laud Misc. 114](https://medieval.bodleian.ox.ac.uk/catalog/manuscript_6923) has the heading 'Pershore Legendary'. If I [search for this heading](https://medieval.bodleian.ox.ac.uk/?utf8=✓&q=pershore+legendary), however, it does not show up. I assume this is how people would normally look for named manuscripts.

**Comment by andrew-morrison** [comment]
The `<head>` is being indexed, and MS. Laud Misc. 114 is the only match if you make it a [phrase search](https://medieval.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=%22pershore+legendary%22), but the relevance algorithm is placing it on page two of the results. That is surprising, but there are various factors which can interact in unexpected ways.

On QA I have boosted the ms_summary_sm field - which is what is displayed under the shelfmark in search results for manuscripts as their "contents" - so that any keywords which match there are now considered as relevant matches in titles, double matches elsewhere, all else being equal. This summary field will be the `<head>` if there is one in the source TEI, if not then `<summary>` inside msContents (or for each msPart), if not then it constructs a summary from the work titles/authors and manuscript origins. All of those deserve to be boosted, and probably should've been all along, so I don't think it will be a problem to apply this to all TEI catalogues. But please take a look, test a few different queries by comparing QA to PRD (although the former currently has newer data than the latter), and let me know what you think. It will require a redeploy, and a few minutes downtime, which I cannot do this week.

**Comment by andrew-morrison** [comment]
Have you had a chance to test the boosting of text in `<head>` (or `<summary>`) on QA? It certainly helps for finding the Pershore Legendary. Unless you have any other examples of relevance ranking not working as expected, even on QA, I think I should push this to production the next time it needs updating (I'm working on some improvements to accessibility.)

**Comment by andrew-morrison** [comment]
I've implemented the boosting heads and summaries on the production system.
