### ISSUE TITLE
library missing from processing directory?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#407]
I think there is a folder called "lib" or "library" missing which stops "previewMs" and "converttohtml" from working. (They work locally because I have a local copy on my machine). Not a major problem but makes it a bit more complicated to set up previewMs for new starters and to share the code with others.

**Comment by andrew-morrison** [comment]
The _lib_ folder is created by the indexing script, which downloads everything first, so that it doesn't need to make thousands of requests to GitHub, to get the common templates used by all TEI catalogues for every record. But, as I have that in my local copy from running the weekly indexing, I'd forgotten new starters wouldn't.

I've rearranged the code to fix this. Now, when previewing, it will download the library XSLT from GitHub each time. That does mean previewing might be a bit slower if on a slow connection, or not possible at all if offline.

I've tested it, and it makes no difference to what appears on the web site. Pull the latest changes, delete your local _lib_ folder, and confirm the preview still works. If it works for you then it should work for anyone so please close this issue.
