### ISSUE TITLE
adding more subject headings

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#479]
Before these can be merged in from the spreadsheet, I need to turn the existing `note type="subject"` markup into `term type="subject"` (as discussed over email), which in turn will require an update to the indexing scripts - @andrew-morrison when would be a good time to do this?

**Comment by andrew-morrison** [comment]
I've modified the indexing script for works so you can use either...
```
<note type="subject">sermons</note>
```
...or...
```
<term ref="#subject_sermons"/>
```
...or both at the same time. Either will cause the work in which it is found being indexed with the "sermons" subject.

I don't have time at the moment to write a script to update works.xml from the spreadsheet of subjects, nor change the indexing script for manuscript to add subjects as a facet.

**Comment by andrew-morrison** [comment]
I've found the time to write a script to update works.xml from the spreadsheet of subjects.

There are some works that have subjects in works.xml, but aren't in the spreadsheet. For example, [this work](https://medieval.bodleian.ox.ac.uk/catalog/work_7602), which currently has the subject 'classical literature'. Do you want those to be stripped of their subjects, so that works.xml only contains the classifications that are in the spreadsheet? Or do you want works not in the spreadsheet to retain their current subjects?

Let me know which option you'd prefer, and I'll run it, then commit to a branch and create a pull request. (It may avoid conflicts when merging if you commit and push any changes you're currently working on in works.xml first, if any.)

**Comment by holfordm** [comment]
Many thanks @andrew-morrison ! 
Quite a number of new works have been added over the last year - these won't be in the spreadsheet (which was generated early last year I think), but their subjects will still be correct, and should be retained.
