### ISSUE TITLE
ODD should be included in repo?

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#57]

**Comment by jamescummings** [comment]
No, it explicitly shouldn't, otherwise people will start re-introducing per-repository changes. The whole point of the project is to have one ODD to rule them all. The ODD and its repo are available on github and so can be forked, modified, etc. and taken over, but it should certainly be a separate repository not related to any one catalogue.

**Comment by holfordm** [comment]
Sorry I didn't mean in this repo (I accept this this was unclear!!) but in the Bodleian repo https://github.com/bodleian

**Comment by jamescummings** [comment]
Ah, then definitely.  I mean they might want to wait until I'm gone, just in case I make changes to the schema in ingesting the other catalogues (working on Fihrist now).... but they are free to fork https://github.com/jamescummings/Bodleian-msDesc-ODD/  I should remove the tolkein2HTML script from there since it is out of date.

**Comment by holfordm** [comment]
Would you consider moving the master copy of the ODD to the Bodleian repo in the near future? I feel that the current version should be publicly available in the Bodleian repo when the first catalogue site goes live which will probably be early August.

**Comment by ahankinson** [comment]
I could create a new repo called "tei-catalogue-schema"?

**Comment by holfordm** [comment]
Yes, please do. @jamescummings, I assume we may now fork the ODD to the Bodleian repo? (which will then become the master copy?)

**Comment by ahankinson** [comment]
It is here: https://github.com/bodleian/consolidated-tei-schema
