### ISSUE TITLE
Split altIdentifier/idno on comma

### ISSUE THREAD

**Issue by jamescummings** [bodleian/medieval-mss#6]
Hey @holfordm,

I remember you wanting me to split altIdentifer/idno on commas e.g. where it has something like 
"18914, 18915, 18916, 18917, 18918" e.g. in Canon_Bibl_Lat/Canon_Bibl_Lat_0022.xml
which is fair enough.  But any suggestions on how I tell the difference between instances like that and those like:
"Not in SC (late accession): description unpublished, only available in Library"
"MS. Lat. misc. b. 13, fol. 50"
"P. Oxy. III 410, III 464"

Would an acceptable compromise be where the altIdentifier/idno contains any a-Z letter I **do not** split it but where it just contains numbers and punctuation then I **do** split it?

So the "18914, 18915, 18916, 18917, 18918" above would split fine, none of the others above or things like "30138 ('Greek Inscription 4'), 30826 ('Gr. Inscr. 4')" would be split?

**Comment by holfordm** [comment]
We can address this by idno/@type.
type="SCN" -- it should always be possible to split these by comma. There will be some left over with hyphens to tidy up manually.
type="TM" -- it should always be possible to split these by comma. 
type="PR" -- these are too complicated to split and are less significant anyway since (unlike TM) they don't map to URIs.
any other type: ignore.

**Comment by jamescummings** [comment]
Ah ok. That is even easier than what I implemented. Will change it to that.

**Comment by jamescummings** [comment]
I believe this is done, so I'm closing it. re-open if it is still a problem.
