### ISSUE TITLE
move to new Zotero library

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#63]
https://www.zotero.org/bodleianwmss/

**Comment by IgnatG** [comment]
Can I ask if you could check the settings for both the old link and the new one and make sure that they are the same? (https://www.zotero.org/bodleianwmss/ and https://www.zotero.org/groups/434020/bodleian_library_western_medieval_manuscripts_bibliography)

I've seen that under Settings->Privacy there is a checkbox asking if you want to Publish the entire library. Can you look at the old link's settings to see if this box is checked and maybe do the same for the new link. I'm asking this because at the moment I can't see anything - not sure if it's because of that or something else.

**Comment by holfordm** [comment]
Sorry I should have given you a URL based on the user ID

api.zotero.org/users/3118282

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IgnatG** [comment]
that's better. Just to confirm: the new URL is already populated with the same content as the previous one? or is it empty now? I can't tell for sure...that's why I'm asking.

**Comment by holfordm** [comment]
It should have much more content than the other one

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by IgnatG** [comment]
fixed: moved to the new URL
