### ISSUE TITLE
crossreferences in personal names index

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#66]
in persons.xml some names are given type="crossref". This is to help someone browsing the list who might look (say) for Geoffrey Chaucer under G rather than C. My intention was that the "crossref" form would create a link to the main form (as in the ecodices person index http://www.e-codices.unifr.ch/en/person_index). Is this possible? If not, would it be possible to have multiple "display" forms for a single person - in which case the person index would have entries for both "Geoffrey Chaucer" and "Chaucer, Geoffrey" both of which would link to ../person_100185203

**Comment by ahankinson** [comment]
I anticipate that people wanting to find records of "Chaucer" will use the big search bar at the top and input "Chaucer." Searching for "[Geoffry Chaucer](http://medieval-qa.bodleian.ox.ac.uk/?utf8=✓&f%5Btype%5D%5B%5D=person&q=Geoffry+Chaucer)" will give you the record for Chaucer, Geoffrey. Surprisingly, even searching for "[Jeff Chaucer](http://medieval-qa.bodleian.ox.ac.uk/?utf8=✓&f%5Btype%5D%5B%5D=person&q=Jeff+Chaucer)" and even "[Čoser](http://medieval-qa.bodleian.ox.ac.uk/?utf8=✓&f%5Btype%5D%5B%5D=person&q=Čoser)"will give you the correct record as well.

It seems that the 'crossref' attribute will only provide varying forms of access on the record itself. So, for example, person_47 has a cross ref of "Stainsby, see Alexander of Stainsby", but this would only appear once you visit the record for "Alexander of Stainsby."

The alternative is to make "Stainsby, see Alexeander of Stainsby" a person record in itself, so that if someone clicks on the "S" in the alphabetical facet (and after paging through to the appropriate results page) finds the record only to discover that it's instead indexed under "A". 

So I think by doing the variant forms of the name, and assuming that people will first try to find their person by typing it in, will result in a much more effective search interface. 

We can certainly *display* the `@crossref` values, but again that would be strange to have the crossref value on the record itself. Also, the actual values in `@crossref` vary considerably: Some have `foreName/surname` child elements, while others are in written form, and still others have "XXX, see YYY".
