### ISSUE TITLE
author pages should link to works? 

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#79]
This would be helpful, since it is currently possible to miss index entries for works due to variant spellings.
E.g., search for "mirfield" brings up the entry for "Mirfeld, John, -1407" (as the variant spelling is captured there), but not the work entry Mirfeld, John, -1407: Breuiarium bartholomaei [Latin] (because the variant spelling is not captured there)

**Comment by andrew-morrison** [comment]
I've implemented this on the QA site:

http://medieval-qa.bodleian.ox.ac.uk/catalog/person_84812388

It was also a request during the Fihrist training but I'm currently overhauling the indexing scripts for Medieval, which I'll then adapt for Fihrist and the rest. It is only with the more efficient XQuery developed for #148 that this is feasible.

If an author has only got one work then the link takes you to a page with the same list of manuscripts (or a subset if they have another role as well as author) but with the changes for #34 there is a chance of there being notes, external links or a bibliography on the work page (e.g. http://medieval-qa.bodleian.ox.ac.uk/catalog/person_72430265.)

And at the other extreme, for the most prolific authors, it pushes the links to manuscripts a long way down the page:

http://medieval-qa.bodleian.ox.ac.uk/catalog/person_66806872

The reverse - links to authors from works - could also be added.

**Comment by andrew-morrison** [comment]
Works now link to authors on QA.

**Comment by holfordm** [comment]
I am waiting for feedback from Martin on this and #34. 
Two queries:
- is there any sorting of works by title, if so how does it work?
- how are the links to works generated? I guess it is a collection of the works associated with an author in the manuscript files, linked to the relevant authority records. It would also be possible (and perhaps neater?) to generate it just from the works authority file, since that includes all the author detals for works where authors have clearly been identified

**Comment by andrew-morrison** [comment]
Sorting of works has been by ID (alphabetically, so work_1 and work_100 came before work_2 and then work_200) but I've recently figured out how to stop Blacklight doing that, and can now control the order of all such lists in the XQuery. So now they're sorted alphabetically by the link text (which is the `title` of `@type` "uniform" in the works.xml authority file).

The list is generated by combining both the association of authors to works in the works.xml authority file and the association of authors to works by being in the same `msItem` in a TEI record. So, for example, [this work](http://medieval-qa.bodleian.ox.ac.uk/catalog/work_5752) has two authors: [Augustine](http://medieval-qa.bodleian.ox.ac.uk/catalog/person_66806872) because he's the `author` in works.xml and [Quodvultdeus](http://medieval-qa.bodleian.ox.ac.uk/catalog/person_250796368) because he's the `author` that's in the same `msItem` as `<title key="work_5752">Aduersus Quinque Haereses</title>` in Merton_College_MS_3.xml.

I've set it up that way because then it will work for other catalogues, which don't have any author-to-work associations in their authority files. But I can change it for Medieval so that only the authority files are used. Doing so will reduce the total number of work links on all the person pages from 120,926 to 120,333 (and the total number of author links on work pages from 151,751 to 151,707.)

**Comment by holfordm** [comment]
I think approach (b) just using the works files is preferable; it will miss a few things (but many of them are not true 'works' in any case), but it will avoid unexpected combinations, such as the co-occurence of Virgil and Pseudo Ovid in this record (http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_3921), item 2, which turns Ps-Ovid into an author of the Georgics here (http://medieval-qa.bodleian.ox.ac.uk/catalog/person_285292080)

**Comment by andrew-morrison** [comment]
I've made that change.

Should people be likewise only included as an Author in the Roles filter if they're in the works.xml authority file? For example, [Corsini](http://medieval-qa.bodleian.ox.ac.uk/catalog/person_71827949) has no works listed despite being [included as an author in the role filter of the people search](http://medieval-qa.bodleian.ox.ac.uk/?f%5Broles_sm%5D%5B%5D=Author&f%5Btype%5D%5B%5D=person&q=Corsini) because he has been tagged as `<persName key="person_71827949" role="author" cert="low">Corsini</persName>` in a note inside a work in [MS. Ital. e. 13](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_6292). Likewise [Campanus](http://medieval-qa.bodleian.ox.ac.uk/catalog/person_68979356), who definitely is an author, but only of an epigram which is one of many small items in [MS. Sparrow 2](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_9501) not in works.xml.

**Comment by holfordm** [comment]
Roles should contine to be based on the manuscript records - because, as you say, there are some people identified as authors in the manuscript records who don't, for various reasons, have works authority files

**Comment by holfordm** [comment]
One additional question is whether `author role="translator"` in works.xml should be picked up here, creating a section "translator of" to come after "author of". Walter Hilton (person_2597190) would be an example of an affected author, also the translator of work_3968

**Comment by andrew-morrison** [comment]
OK, I'll add "Translator of" lists.

**Comment by andrew-morrison** [comment]
This has been implemented on QA. For example...

http://medieval-qa.bodleian.ox.ac.uk/catalog/person_35253721

...has a "Translator of" field with a link to...

http://medieval-qa.bodleian.ox.ac.uk/catalog/work_375

...which has a "Translator(s)" field with a link back again.

As discussed above with authors, this is based solely on `author` elements with a role of "translator" in the works.xml authority file. So, while there are 128 translators according to the Role filter on the People search (based on `persName` elements with a role of "translator" in all the manuscript files), only 18 of those have "Translator of" fields, because those are the only ones currently identified in the works.xml (there is a 19th, but the key is "person_person_79254124" which would be broken link, so that is skipped.)
