### ISSUE TITLE
set up procedures for site updates

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#84]

**Comment by ahankinson** [comment]
Could you please provide more context? Are you wanting anyone to be able to provide site updates?

**Comment by holfordm** [comment]
Sure! I'm open to your suggestions here and the procedure may be different for the different catalogues. I think we would want to update monthly at the moment. If it's easier for me to run the scripts than for someone at BDLSS to do that, that's OK with me. Although you will probably need to run them through with me again. I assume that updates will apply initially to the QA site and when that has been checked, someone at BDLSS (you?) will switch them over to the main site.

**Comment by ahankinson** [comment]
All the tools for you to update the site are available in the repository, and the README should tell you how to do it.

The only special thing I have is a little shell script that looks like this:

```
#!/usr/bin/env bash

./generate-html.sh
./generate-solr-document.sh manuscripts.xquery mss_solr_index.xml manuscript solr01-qa.bodleian.ox.ac.uk
./generate-solr-document.sh places.xquery places_solr_index.xml place solr01-qa.bodleian.ox.ac.uk
./generate-solr-document.sh organizations.xquery organizations_solr_index.xml organization solr01-qa.bodleian.ox.ac.uk
./generate-solr-document.sh people.xquery people_solr_index.xml person solr01-qa.bodleian.ox.ac.uk
./generate-solr-document.sh works.xquery works_solr_index.xml work solr01-qa.bodleian.ox.ac.uk
```

Which I call 'index-all-qa.sh'. As you can see, all it does is create the HTML, and then index and upload the appropriate data type to the QA solr system. (I've got a similar one that I run for production). I just did this so I only had to run one command instead of five.

The only thing required is a working Java installation, and access to the QA systems. This may require access to our special BDLSS VPN, but there are probably ways around that.
