### ISSUE TITLE
msPart/altIdentifier should display

### ISSUE THREAD

**Issue by holfordm** [bodleian/medieval-mss#96]
## Detailed Description
Information in the TEI record in msPart/altIdentifier should display in the HTML record. 

## Link to Page
Examples: 
https://medieval.bodleian.ox.ac.uk/catalog/manuscript_4947 - information about upper and lower script in the record is lost
https://medieval.bodleian.ox.ac.uk/catalog/manuscript_959 - information about the extent of the different units is lost

## Context
msPart/altIdentifier can contain information about the extent of a part that is essential for understanding the record. 

## Possible Implementation
@ahankinson , I think the display of msPart information is handled by Blacklight. l. 563 in convert2HTML is where the relevant html would be created.

**Comment by andrew-morrison** [comment]
So, instead of headings such as...

Manuscript Part 1
Manuscript Part 2

...do you want headings with the idno values appended, such as...

Manuscript Part 1: MS. Gr. bib. d. 2 (P) - upper script
Manuscript Part 2: MS. Gr. bib. d. 2 (P) - lower script

...and when there are notes maybe add them as a line beneath, possibly in italic, like this...

Manuscript Part 1: MS. Barocci 133 - Part A
_fols. 1 and 228_
Manuscript Part 2: MS. Barocci 133 - Part B
_fols. 2-9_

...or get rid of the "Manuscript Part N" completely and rely on whatever has been catalogued in altIdentifier?

**Comment by holfordm** [comment]
I think option (c), "get rid of the "Manuscript Part N" completely and rely on whatever has been catalogued in altIdentifier" - just display the string value of elements in `<altIdentifier>` (should just be `<idno>` and sometimes `<note>`. There may be a little tidying up to do for consistency but I will take care of that.

**Comment by andrew-morrison** [comment]
I've implemented this change. It will put the contents of the note element in parentheses unless it already begins with an opening bracket.

It fixes a bug that multiple levels of msPart (i.e. parts within parts) caused the numbering to reset. For example, in MS. Douce d. 19, parts 10a-c are headed as extra parts 1-3 [on production](https://medieval.bodleian.ox.ac.uk/catalog/manuscript_4766), but now [on QA](http://medieval-qa.bodleian.ox.ac.uk/catalog/manuscript_4766) that's fixed.

Attached is a spreadsheet listing which part headings have changed: [changed_part_headings.xlsx](https://github.com/bodleian/medieval-mss/files/1535022/changed_part_headings.xlsx)
